
(defpackage "LP-SOLVER-FFI"
  (:use "COMMON-LISP" "CFFI")
  (:export "CREATE-LP" "DESTROY-LP" "WITH-LP" "CALL-WITH-LP" "SOLVER-ERROR"
           "SOLVER-ERROR-OPERATION" "SOLVER-ERROR-STATUS" "SOLVER-ERROR-MESSAGE"
           "VERBOSITY-LEVEL" "OBJECTIVE-MODE" "INCREMENTAL-GROWTH-P" "ROW-COUNT"
           "COLUMN-COUNT" "SOLVE-PROGRAM" "OBJECTIVE-PARAMETERS" "CONSTRAINT-PARAMETERS"
           "RIGHT-HAND-VALUE" "CONSTRAINT-TYPE" "INTEGER-VARIABLE-P" "OBJECTIVE-VALUE"
           "SOLUTION-VALUES" "ADD-SOS-CONSTRAINT" "ADD-CONSTRAINT"))



(defpackage "SYMBOLIC-LP"
  (:use "COMMON-LISP" "LP-SOLVER-FFI")
  (:shadow "VARIABLE" "SOLVE-PROGRAM" "ADD-CONSTRAINT")
  (:export "COEFFICIENT" "LINEAR-SUM" "TERM-COEFFICIENT" "TERM-VARIABLE" "NEXT-TERM"
           "FINAL-TERM-P" "CONSTANT-TERM-P" "CONSTANT-SUM-P" "ZERO-SUM-P" "TERM-DESIGNATOR"
           "TERM" "MAP-OVER-TERMS" "DO-TERMS" "$PRODUCT" "$SUM" "$DIFFERENCE" "$+" "$-" "$*"
           "$<=" "$=" "$>=" "MAKE-CONSTRAINT" "CONSTRAINT-LEFT-SIDE" "CONSTRAINT-RELATION"
           "CONSTRAINT-RIGHT-SIDE" "CONSTRAINT-TAG" "CONSTRAINTP" "LINEAR-SUM-P" "WITH-VARIABLE-GENERATORS"
           "VARIABLE" "VARIABLE-NAME" "VARIABLE-TYPE" "VARIABLE-EXCLUSION" "PROGRAM"
           "PROGRAM-OBJECTIVE" "PROGRAM-CONSTRAINTS" "PROGRAM-VARIABLES" "ADD-CONSTRAINT"
           "DECLARE-VARIABLE-EXCLUSION" "DECLARE-VARIABLE-TYPE" "*PROGRAM*" "INTERN-VARIABLE"
           "MINIMIZE-FUNCTION" "MAXIMIZE-FUNCTION" "SOLVE-PROGRAM"))
